// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: core/seed_accessor_protocol.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeedAccessor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstNid        *NodeID `protobuf:"bytes,1,opt,name=dst_nid,json=dstNid,proto3" json:"dst_nid,omitempty"`
	SrcNid        *NodeID `protobuf:"bytes,2,opt,name=src_nid,json=srcNid,proto3" json:"src_nid,omitempty"`
	HopCount      uint32  `protobuf:"varint,3,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	Id            uint32  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Mode          uint32  `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Channel       uint32  `protobuf:"varint,6,opt,name=channel,proto3" json:"channel,omitempty"`
	ModuleChannel uint32  `protobuf:"varint,7,opt,name=module_channel,json=moduleChannel,proto3" json:"module_channel,omitempty"`
	CommandId     uint32  `protobuf:"varint,8,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Content       []byte  `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SeedAccessor) Reset() {
	*x = SeedAccessor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_seed_accessor_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedAccessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedAccessor) ProtoMessage() {}

func (x *SeedAccessor) ProtoReflect() protoreflect.Message {
	mi := &file_core_seed_accessor_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedAccessor.ProtoReflect.Descriptor instead.
func (*SeedAccessor) Descriptor() ([]byte, []int) {
	return file_core_seed_accessor_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SeedAccessor) GetDstNid() *NodeID {
	if x != nil {
		return x.DstNid
	}
	return nil
}

func (x *SeedAccessor) GetSrcNid() *NodeID {
	if x != nil {
		return x.SrcNid
	}
	return nil
}

func (x *SeedAccessor) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *SeedAccessor) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeedAccessor) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SeedAccessor) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SeedAccessor) GetModuleChannel() uint32 {
	if x != nil {
		return x.ModuleChannel
	}
	return 0
}

func (x *SeedAccessor) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *SeedAccessor) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hint    uint32 `protobuf:"varint,2,opt,name=hint,proto3" json:"hint,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_seed_accessor_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_core_seed_accessor_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_core_seed_accessor_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Auth) GetHint() uint32 {
	if x != nil {
		return x.Hint
	}
	return 0
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *AuthSuccess) Reset() {
	*x = AuthSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_seed_accessor_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSuccess) ProtoMessage() {}

func (x *AuthSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_seed_accessor_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSuccess.ProtoReflect.Descriptor instead.
func (*AuthSuccess) Descriptor() ([]byte, []int) {
	return file_core_seed_accessor_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *AuthSuccess) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type Hint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hint uint32 `protobuf:"varint,1,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *Hint) Reset() {
	*x = Hint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_seed_accessor_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hint) ProtoMessage() {}

func (x *Hint) ProtoReflect() protoreflect.Message {
	mi := &file_core_seed_accessor_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hint.ProtoReflect.Descriptor instead.
func (*Hint) Descriptor() ([]byte, []int) {
	return file_core_seed_accessor_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Hint) GetHint() uint32 {
	if x != nil {
		return x.Hint
	}
	return 0
}

var File_core_seed_accessor_protocol_proto protoreflect.FileDescriptor

var file_core_seed_accessor_protocol_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x63, 0x6f, 0x6c, 0x6f, 0x6e, 0x69, 0x6f, 0x2e, 0x53, 0x65, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x1a, 0x0f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x0c, 0x53, 0x65, 0x65, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x5f, 0x6e, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x6e, 0x69, 0x6f, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x52, 0x06, 0x64, 0x73, 0x74, 0x4e,
	0x69, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x5f, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x6e, 0x69, 0x6f, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x52, 0x06, 0x73, 0x72, 0x63, 0x4e, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x0e,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x04,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x68, 0x69,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x1a, 0x0a, 0x04, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6c, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x64, 0x61, 0x2d, 0x6a, 0x70, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x6e, 0x69, 0x6f, 0x2d, 0x73,
	0x65, 0x65, 0x64, 0x2f, 0x73, 0x65, 0x65, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_seed_accessor_protocol_proto_rawDescOnce sync.Once
	file_core_seed_accessor_protocol_proto_rawDescData = file_core_seed_accessor_protocol_proto_rawDesc
)

func file_core_seed_accessor_protocol_proto_rawDescGZIP() []byte {
	file_core_seed_accessor_protocol_proto_rawDescOnce.Do(func() {
		file_core_seed_accessor_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_seed_accessor_protocol_proto_rawDescData)
	})
	return file_core_seed_accessor_protocol_proto_rawDescData
}

var file_core_seed_accessor_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_seed_accessor_protocol_proto_goTypes = []interface{}{
	(*SeedAccessor)(nil), // 0: colonio.SeedAccessorProtocol.SeedAccessor
	(*Auth)(nil),         // 1: colonio.SeedAccessorProtocol.Auth
	(*AuthSuccess)(nil),  // 2: colonio.SeedAccessorProtocol.AuthSuccess
	(*Hint)(nil),         // 3: colonio.SeedAccessorProtocol.Hint
	(*NodeID)(nil),       // 4: colonio.core.NodeID
}
var file_core_seed_accessor_protocol_proto_depIdxs = []int32{
	4, // 0: colonio.SeedAccessorProtocol.SeedAccessor.dst_nid:type_name -> colonio.core.NodeID
	4, // 1: colonio.SeedAccessorProtocol.SeedAccessor.src_nid:type_name -> colonio.core.NodeID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_seed_accessor_protocol_proto_init() }
func file_core_seed_accessor_protocol_proto_init() {
	if File_core_seed_accessor_protocol_proto != nil {
		return
	}
	file_core_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_core_seed_accessor_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedAccessor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_seed_accessor_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_seed_accessor_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_seed_accessor_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_seed_accessor_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_seed_accessor_protocol_proto_goTypes,
		DependencyIndexes: file_core_seed_accessor_protocol_proto_depIdxs,
		MessageInfos:      file_core_seed_accessor_protocol_proto_msgTypes,
	}.Build()
	File_core_seed_accessor_protocol_proto = out.File
	file_core_seed_accessor_protocol_proto_rawDesc = nil
	file_core_seed_accessor_protocol_proto_goTypes = nil
	file_core_seed_accessor_protocol_proto_depIdxs = nil
}
