apiVersion: v1
kind: ConfigMap
metadata:
  name: seed
  namespace: colonio-simulator
data:
  seed.json: |
    {
      "port": 8443,
      "certFile": "../seed.crt",
      "keyFile": "../seed.key",
      "useTcp": true,
      "cluster": {
        "revision": 1,
        "sessionTimeout": "30s",
        "pollingTimeout": "10s",
        "iceServers": [],
        "keepaliveInterval": "10s",
        "bufferInterval": "10ms",
        "webrtcPacketBaseBytes": 16384,
        "routingExchangeInterval": "1m",
        "seedConnectRate": 3,
        "seedReconnectDuration": "3m",
        "geometry": {
          "sphere": {
            "radius": 6378137
          }
        },
        "spread": {
          "cacheLifetime": "1m"
        }
      },
      "seedPath": "/seed"
    }