apiVersion: v1
kind: Service
metadata:
  name: coturn
spec:
  ports:
  - port: 3478
    name: main
  - port: 5349
    name: tls
  selector:
    app: coturn
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coturn
spec:
  selector:
    matchLabels:
      app: coturn
  serviceName: coturn
  replicas: 1
  template:
    metadata:
      labels:
        app: coturn
    spec:
      containers:
      - name: coturn
        image: coturn/coturn:4.6.2
        ports:
        - containerPort: 3478
          name: main
        - containerPort: 5349
          name: tls
