// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/protocol.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coordinate struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb00a8495aa3e3a, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type NodeID struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Id0                  uint64   `protobuf:"varint,2,opt,name=id0,proto3" json:"id0,omitempty"`
	Id1                  uint64   `protobuf:"varint,3,opt,name=id1,proto3" json:"id1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeID) Reset()         { *m = NodeID{} }
func (m *NodeID) String() string { return proto.CompactTextString(m) }
func (*NodeID) ProtoMessage()    {}
func (*NodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb00a8495aa3e3a, []int{1}
}

func (m *NodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeID.Unmarshal(m, b)
}
func (m *NodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeID.Marshal(b, m, deterministic)
}
func (m *NodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeID.Merge(m, src)
}
func (m *NodeID) XXX_Size() int {
	return xxx_messageInfo_NodeID.Size(m)
}
func (m *NodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeID.DiscardUnknown(m)
}

var xxx_messageInfo_NodeID proto.InternalMessageInfo

func (m *NodeID) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NodeID) GetId0() uint64 {
	if m != nil {
		return m.Id0
	}
	return 0
}

func (m *NodeID) GetId1() uint64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_BoolV
	//	*Value_IntV
	//	*Value_DoubleV
	//	*Value_StringV
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_adb00a8495aa3e3a, []int{2}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_BoolV struct {
	BoolV bool `protobuf:"varint,1,opt,name=bool_v,json=boolV,proto3,oneof"`
}

type Value_IntV struct {
	IntV int64 `protobuf:"varint,2,opt,name=int_v,json=intV,proto3,oneof"`
}

type Value_DoubleV struct {
	DoubleV float64 `protobuf:"fixed64,3,opt,name=double_v,json=doubleV,proto3,oneof"`
}

type Value_StringV struct {
	StringV []byte `protobuf:"bytes,4,opt,name=string_v,json=stringV,proto3,oneof"`
}

func (*Value_BoolV) isValue_Value() {}

func (*Value_IntV) isValue_Value() {}

func (*Value_DoubleV) isValue_Value() {}

func (*Value_StringV) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetBoolV() bool {
	if x, ok := m.GetValue().(*Value_BoolV); ok {
		return x.BoolV
	}
	return false
}

func (m *Value) GetIntV() int64 {
	if x, ok := m.GetValue().(*Value_IntV); ok {
		return x.IntV
	}
	return 0
}

func (m *Value) GetDoubleV() float64 {
	if x, ok := m.GetValue().(*Value_DoubleV); ok {
		return x.DoubleV
	}
	return 0
}

func (m *Value) GetStringV() []byte {
	if x, ok := m.GetValue().(*Value_StringV); ok {
		return x.StringV
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_BoolV)(nil),
		(*Value_IntV)(nil),
		(*Value_DoubleV)(nil),
		(*Value_StringV)(nil),
	}
}

func init() {
	proto.RegisterType((*Coordinate)(nil), "colonio.Protocol.Coordinate")
	proto.RegisterType((*NodeID)(nil), "colonio.Protocol.NodeID")
	proto.RegisterType((*Value)(nil), "colonio.Protocol.Value")
}

func init() { proto.RegisterFile("core/protocol.proto", fileDescriptor_adb00a8495aa3e3a) }

var fileDescriptor_adb00a8495aa3e3a = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xb3, 0x26, 0x9b, 0xd6, 0xa1, 0x42, 0x19, 0x11, 0x03, 0x5e, 0x4a, 0x4e, 0x39, 0x55,
	0x8b, 0x7f, 0x40, 0xaa, 0x87, 0x78, 0x11, 0xd9, 0x43, 0x0e, 0x5e, 0x42, 0x93, 0x2c, 0xb2, 0xb0,
	0xec, 0x94, 0xb8, 0x5d, 0x1a, 0x7f, 0xbd, 0xec, 0xc4, 0x9e, 0xf6, 0xbd, 0xef, 0x3d, 0xde, 0xc2,
	0xc0, 0x6d, 0x4f, 0xa3, 0x7e, 0x3c, 0x8e, 0xe4, 0xa9, 0x27, 0xbb, 0x65, 0x81, 0xeb, 0x9e, 0x2c,
	0x39, 0x43, 0xdb, 0xcf, 0x7f, 0x5e, 0x56, 0x00, 0xaf, 0x44, 0xe3, 0x60, 0xdc, 0xc1, 0x6b, 0x5c,
	0x81, 0x38, 0x17, 0x62, 0x23, 0x2a, 0xa1, 0xc4, 0x39, 0xba, 0xa9, 0xb8, 0x9a, 0xdd, 0x54, 0xbe,
	0x40, 0xfe, 0x41, 0x83, 0x7e, 0x7f, 0x43, 0x84, 0xcc, 0x4f, 0x47, 0xcd, 0xc5, 0x1b, 0xc5, 0x1a,
	0xd7, 0x90, 0x9a, 0xe1, 0x89, 0xdb, 0x99, 0x8a, 0x72, 0x26, 0xbb, 0x22, 0xbd, 0x90, 0x5d, 0xf9,
	0x0b, 0xb2, 0x39, 0xd8, 0x93, 0xc6, 0x7b, 0xc8, 0x3b, 0x22, 0xdb, 0x06, 0x9e, 0x58, 0xd6, 0x89,
	0x92, 0xd1, 0x37, 0x78, 0x07, 0xd2, 0x38, 0xdf, 0x06, 0xde, 0x49, 0xeb, 0x44, 0x65, 0xc6, 0xf9,
	0x06, 0x1f, 0x60, 0x39, 0xd0, 0xa9, 0xb3, 0xba, 0x0d, 0xbc, 0x27, 0xea, 0x44, 0x2d, 0x66, 0xc2,
	0xe1, 0x8f, 0x1f, 0x8d, 0xfb, 0x6e, 0x43, 0x91, 0x6d, 0x44, 0xb5, 0x8a, 0xe1, 0x4c, 0x9a, 0xfd,
	0x02, 0x64, 0x88, 0x5f, 0xee, 0xaf, 0xeb, 0xf4, 0x4b, 0xf2, 0x11, 0xba, 0x9c, 0x9f, 0xe7, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x7f, 0x6e, 0xdd, 0x22, 0x01, 0x00, 0x00,
}
