// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/node_accessor_protocol.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeAccessor struct {
	DstNid               *NodeID  `protobuf:"bytes,1,opt,name=dst_nid,json=dstNid,proto3" json:"dst_nid,omitempty"`
	SrcNid               *NodeID  `protobuf:"bytes,2,opt,name=src_nid,json=srcNid,proto3" json:"src_nid,omitempty"`
	Id                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Mode                 uint32   `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Channel              uint32   `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	CommandId            uint32   `protobuf:"varint,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Content              []byte   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeAccessor) Reset()         { *m = NodeAccessor{} }
func (m *NodeAccessor) String() string { return proto.CompactTextString(m) }
func (*NodeAccessor) ProtoMessage()    {}
func (*NodeAccessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{0}
}

func (m *NodeAccessor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAccessor.Unmarshal(m, b)
}
func (m *NodeAccessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAccessor.Marshal(b, m, deterministic)
}
func (m *NodeAccessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAccessor.Merge(m, src)
}
func (m *NodeAccessor) XXX_Size() int {
	return xxx_messageInfo_NodeAccessor.Size(m)
}
func (m *NodeAccessor) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAccessor.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAccessor proto.InternalMessageInfo

func (m *NodeAccessor) GetDstNid() *NodeID {
	if m != nil {
		return m.DstNid
	}
	return nil
}

func (m *NodeAccessor) GetSrcNid() *NodeID {
	if m != nil {
		return m.SrcNid
	}
	return nil
}

func (m *NodeAccessor) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeAccessor) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *NodeAccessor) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *NodeAccessor) GetCommandId() uint32 {
	if m != nil {
		return m.CommandId
	}
	return 0
}

func (m *NodeAccessor) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ICE struct {
	LocalNid             *NodeID  `protobuf:"bytes,1,opt,name=local_nid,json=localNid,proto3" json:"local_nid,omitempty"`
	RemoteNid            *NodeID  `protobuf:"bytes,2,opt,name=remote_nid,json=remoteNid,proto3" json:"remote_nid,omitempty"`
	Ice                  string   `protobuf:"bytes,3,opt,name=ice,proto3" json:"ice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ICE) Reset()         { *m = ICE{} }
func (m *ICE) String() string { return proto.CompactTextString(m) }
func (*ICE) ProtoMessage()    {}
func (*ICE) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{1}
}

func (m *ICE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ICE.Unmarshal(m, b)
}
func (m *ICE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ICE.Marshal(b, m, deterministic)
}
func (m *ICE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICE.Merge(m, src)
}
func (m *ICE) XXX_Size() int {
	return xxx_messageInfo_ICE.Size(m)
}
func (m *ICE) XXX_DiscardUnknown() {
	xxx_messageInfo_ICE.DiscardUnknown(m)
}

var xxx_messageInfo_ICE proto.InternalMessageInfo

func (m *ICE) GetLocalNid() *NodeID {
	if m != nil {
		return m.LocalNid
	}
	return nil
}

func (m *ICE) GetRemoteNid() *NodeID {
	if m != nil {
		return m.RemoteNid
	}
	return nil
}

func (m *ICE) GetIce() string {
	if m != nil {
		return m.Ice
	}
	return ""
}

type Offer struct {
	PrimeNid             *NodeID  `protobuf:"bytes,1,opt,name=prime_nid,json=primeNid,proto3" json:"prime_nid,omitempty"`
	SecondNid            *NodeID  `protobuf:"bytes,2,opt,name=second_nid,json=secondNid,proto3" json:"second_nid,omitempty"`
	Sdp                  string   `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{2}
}

func (m *Offer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offer.Unmarshal(m, b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
}
func (m *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(m, src)
}
func (m *Offer) XXX_Size() int {
	return xxx_messageInfo_Offer.Size(m)
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetPrimeNid() *NodeID {
	if m != nil {
		return m.PrimeNid
	}
	return nil
}

func (m *Offer) GetSecondNid() *NodeID {
	if m != nil {
		return m.SecondNid
	}
	return nil
}

func (m *Offer) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

func (m *Offer) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type OfferSuccess struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	SecondNid            *NodeID  `protobuf:"bytes,2,opt,name=second_nid,json=secondNid,proto3" json:"second_nid,omitempty"`
	Sdp                  string   `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferSuccess) Reset()         { *m = OfferSuccess{} }
func (m *OfferSuccess) String() string { return proto.CompactTextString(m) }
func (*OfferSuccess) ProtoMessage()    {}
func (*OfferSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{3}
}

func (m *OfferSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferSuccess.Unmarshal(m, b)
}
func (m *OfferSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferSuccess.Marshal(b, m, deterministic)
}
func (m *OfferSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferSuccess.Merge(m, src)
}
func (m *OfferSuccess) XXX_Size() int {
	return xxx_messageInfo_OfferSuccess.Size(m)
}
func (m *OfferSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_OfferSuccess proto.InternalMessageInfo

func (m *OfferSuccess) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OfferSuccess) GetSecondNid() *NodeID {
	if m != nil {
		return m.SecondNid
	}
	return nil
}

func (m *OfferSuccess) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type OfferFailure struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	PrimeNid             *NodeID  `protobuf:"bytes,2,opt,name=prime_nid,json=primeNid,proto3" json:"prime_nid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferFailure) Reset()         { *m = OfferFailure{} }
func (m *OfferFailure) String() string { return proto.CompactTextString(m) }
func (*OfferFailure) ProtoMessage()    {}
func (*OfferFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{4}
}

func (m *OfferFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferFailure.Unmarshal(m, b)
}
func (m *OfferFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferFailure.Marshal(b, m, deterministic)
}
func (m *OfferFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferFailure.Merge(m, src)
}
func (m *OfferFailure) XXX_Size() int {
	return xxx_messageInfo_OfferFailure.Size(m)
}
func (m *OfferFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferFailure.DiscardUnknown(m)
}

var xxx_messageInfo_OfferFailure proto.InternalMessageInfo

func (m *OfferFailure) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OfferFailure) GetPrimeNid() *NodeID {
	if m != nil {
		return m.PrimeNid
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeAccessor)(nil), "colonio.NodeAccessorProtocol.NodeAccessor")
	proto.RegisterType((*ICE)(nil), "colonio.NodeAccessorProtocol.ICE")
	proto.RegisterType((*Offer)(nil), "colonio.NodeAccessorProtocol.Offer")
	proto.RegisterType((*OfferSuccess)(nil), "colonio.NodeAccessorProtocol.OfferSuccess")
	proto.RegisterType((*OfferFailure)(nil), "colonio.NodeAccessorProtocol.OfferFailure")
}

func init() { proto.RegisterFile("core/node_accessor_protocol.proto", fileDescriptor_d6da5911fa8c514f) }

var fileDescriptor_d6da5911fa8c514f = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0x91, 0x64, 0xcb, 0xd5, 0xd4, 0x2e, 0x65, 0x0b, 0x65, 0x29, 0x2d, 0xb8, 0x3a, 0xf9,
	0xe4, 0xd2, 0x96, 0xd2, 0x73, 0x9b, 0x3f, 0xc4, 0x17, 0x27, 0x28, 0xb7, 0x40, 0x10, 0xca, 0xee,
	0x9a, 0x2c, 0x48, 0x3b, 0xca, 0xee, 0xfa, 0x90, 0x27, 0xc8, 0x53, 0xe4, 0x09, 0xf3, 0x12, 0x61,
	0xc7, 0x52, 0x88, 0x0f, 0x21, 0x3a, 0xe4, 0xa4, 0x99, 0xd1, 0xf7, 0xcd, 0xfe, 0x66, 0x18, 0xf8,
	0x2e, 0xd0, 0xaa, 0x1f, 0x06, 0xa5, 0x2a, 0x2b, 0x21, 0x94, 0x73, 0x68, 0xcb, 0xd6, 0xa2, 0x47,
	0x81, 0xf5, 0x92, 0x02, 0xf6, 0x55, 0x60, 0x8d, 0x46, 0xe3, 0x72, 0x8d, 0x52, 0xfd, 0xeb, 0x44,
	0x67, 0x9d, 0xe6, 0xcb, 0x27, 0x6a, 0xb0, 0x6f, 0xc9, 0x1f, 0x22, 0x98, 0x3e, 0x57, 0xb3, 0x9f,
	0x30, 0x91, 0xce, 0x97, 0x46, 0x4b, 0x1e, 0xcd, 0xa3, 0xc5, 0xfb, 0x5f, 0x7c, 0xd9, 0x77, 0xed,
	0x3b, 0x51, 0xfb, 0xd5, 0x61, 0x91, 0x4a, 0xe7, 0xd7, 0x5a, 0x06, 0x8b, 0xb3, 0x82, 0x2c, 0xf1,
	0x6b, 0x16, 0x67, 0x45, 0xb0, 0x7c, 0x80, 0x58, 0x4b, 0x9e, 0xcc, 0xa3, 0xc5, 0xac, 0x88, 0xb5,
	0x64, 0x0c, 0x46, 0x0d, 0x4a, 0xc5, 0x47, 0x54, 0xa1, 0x98, 0x71, 0x98, 0x88, 0xeb, 0xca, 0x18,
	0x55, 0xf3, 0x31, 0x95, 0xfb, 0x94, 0x7d, 0x03, 0x10, 0xd8, 0x34, 0x95, 0x91, 0xa5, 0x96, 0x3c,
	0xa5, 0x9f, 0x59, 0x57, 0x59, 0x49, 0x32, 0xa2, 0xf1, 0xca, 0x78, 0x3e, 0x99, 0x47, 0x8b, 0x69,
	0xd1, 0xa7, 0xf9, 0x5d, 0x04, 0xc9, 0xea, 0xe0, 0x88, 0xfd, 0x81, 0xac, 0x46, 0x51, 0xd5, 0x83,
	0xc6, 0x7c, 0x47, 0xd2, 0x40, 0xfd, 0x17, 0xc0, 0xaa, 0x06, 0xbd, 0x1a, 0x34, 0x6b, 0xb6, 0xd3,
	0x06, 0xe3, 0x47, 0x48, 0xb4, 0x50, 0x34, 0x6f, 0x56, 0x84, 0x30, 0xbf, 0x8f, 0x60, 0x7c, 0xba,
	0xd9, 0x28, 0x1b, 0x58, 0x5a, 0xab, 0x1b, 0x35, 0x8c, 0x85, 0xa4, 0x1d, 0x8b, 0x53, 0x02, 0x8d,
	0x1c, 0xc6, 0xb2, 0xd3, 0x76, 0x2c, 0x4e, 0xb6, 0x3d, 0x8b, 0x93, 0x6d, 0x58, 0xbe, 0xbf, 0x6d,
	0x9f, 0x96, 0x1f, 0xe2, 0xfc, 0x06, 0xa6, 0x84, 0x77, 0xbe, 0xa5, 0xc3, 0x60, 0x9f, 0x21, 0x75,
	0xbe, 0xf2, 0x5b, 0x47, 0x88, 0xb3, 0xa2, 0xcb, 0xde, 0x10, 0x23, 0xbf, 0xec, 0x9e, 0x3c, 0xae,
	0x74, 0xbd, 0xb5, 0xea, 0xc5, 0x27, 0xf7, 0x16, 0x16, 0x0f, 0x5d, 0xd8, 0xff, 0xec, 0x24, 0xb9,
	0x18, 0xd3, 0xd1, 0x5f, 0xa5, 0xf4, 0xf9, 0xfd, 0x18, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xae, 0x9e,
	0x36, 0x53, 0x03, 0x00, 0x00,
}
