// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/colonio/v1alpha/consensus.proto

package v1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation_Command int32

const (
	// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
	Operation_COMMAND_IMPORT Operation_Command = 0
	Operation_COMMAND_GET    Operation_Command = 1
	Operation_COMMAND_SET    Operation_Command = 2
	Operation_COMMAND_PATCH  Operation_Command = 3
	Operation_COMMAND_DELETE Operation_Command = 4
)

// Enum value maps for Operation_Command.
var (
	Operation_Command_name = map[int32]string{
		0: "COMMAND_IMPORT",
		1: "COMMAND_GET",
		2: "COMMAND_SET",
		3: "COMMAND_PATCH",
		4: "COMMAND_DELETE",
	}
	Operation_Command_value = map[string]int32{
		"COMMAND_IMPORT": 0,
		"COMMAND_GET":    1,
		"COMMAND_SET":    2,
		"COMMAND_PATCH":  3,
		"COMMAND_DELETE": 4,
	}
)

func (x Operation_Command) Enum() *Operation_Command {
	p := new(Operation_Command)
	*p = x
	return p
}

func (x Operation_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_api_colonio_v1alpha_consensus_proto_enumTypes[0].Descriptor()
}

func (Operation_Command) Type() protoreflect.EnumType {
	return &file_api_colonio_v1alpha_consensus_proto_enumTypes[0]
}

func (x Operation_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation_Command.Descriptor instead.
func (Operation_Command) EnumDescriptor() ([]byte, []int) {
	return file_api_colonio_v1alpha_consensus_proto_rawDescGZIP(), []int{2, 0}
}

type ConsensusProposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ConsensusProposal_Management
	//	*ConsensusProposal_Operation
	Content       isConsensusProposal_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusProposal) Reset() {
	*x = ConsensusProposal{}
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusProposal) ProtoMessage() {}

func (x *ConsensusProposal) ProtoReflect() protoreflect.Message {
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusProposal.ProtoReflect.Descriptor instead.
func (*ConsensusProposal) Descriptor() ([]byte, []int) {
	return file_api_colonio_v1alpha_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusProposal) GetContent() isConsensusProposal_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ConsensusProposal) GetManagement() *Management {
	if x != nil {
		if x, ok := x.Content.(*ConsensusProposal_Management); ok {
			return x.Management
		}
	}
	return nil
}

func (x *ConsensusProposal) GetOperation() *Operation {
	if x != nil {
		if x, ok := x.Content.(*ConsensusProposal_Operation); ok {
			return x.Operation
		}
	}
	return nil
}

type isConsensusProposal_Content interface {
	isConsensusProposal_Content()
}

type ConsensusProposal_Management struct {
	Management *Management `protobuf:"bytes,1,opt,name=management,proto3,oneof"`
}

type ConsensusProposal_Operation struct {
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

func (*ConsensusProposal_Management) isConsensusProposal_Content() {}

func (*ConsensusProposal_Operation) isConsensusProposal_Content() {}

type Management struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Management) Reset() {
	*x = Management{}
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Management) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Management) ProtoMessage() {}

func (x *Management) ProtoReflect() protoreflect.Message {
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Management.ProtoReflect.Descriptor instead.
func (*Management) Descriptor() ([]byte, []int) {
	return file_api_colonio_v1alpha_consensus_proto_rawDescGZIP(), []int{1}
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       Operation_Command      `protobuf:"varint,1,opt,name=command,proto3,enum=api.colonio.v1alpha.Operation_Command" json:"command,omitempty"`
	OperationId   uint32                 `protobuf:"varint,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_colonio_v1alpha_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *Operation) GetCommand() Operation_Command {
	if x != nil {
		return x.Command
	}
	return Operation_COMMAND_IMPORT
}

func (x *Operation) GetOperationId() uint32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *Operation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Operation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConsensusStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       *ConsensusStateRecords `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusStateSnapshot) Reset() {
	*x = ConsensusStateSnapshot{}
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusStateSnapshot) ProtoMessage() {}

func (x *ConsensusStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusStateSnapshot.ProtoReflect.Descriptor instead.
func (*ConsensusStateSnapshot) Descriptor() ([]byte, []int) {
	return file_api_colonio_v1alpha_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *ConsensusStateSnapshot) GetRecords() *ConsensusStateRecords {
	if x != nil {
		return x.Records
	}
	return nil
}

type ConsensusStateRecords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       map[string][]byte      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusStateRecords) Reset() {
	*x = ConsensusStateRecords{}
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusStateRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusStateRecords) ProtoMessage() {}

func (x *ConsensusStateRecords) ProtoReflect() protoreflect.Message {
	mi := &file_api_colonio_v1alpha_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusStateRecords.ProtoReflect.Descriptor instead.
func (*ConsensusStateRecords) Descriptor() ([]byte, []int) {
	return file_api_colonio_v1alpha_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *ConsensusStateRecords) GetRecords() map[string][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_api_colonio_v1alpha_consensus_proto protoreflect.FileDescriptor

const file_api_colonio_v1alpha_consensus_proto_rawDesc = "" +
	"\n" +
	"#api/colonio/v1alpha/consensus.proto\x12\x13api.colonio.v1alpha\"\xa1\x01\n" +
	"\x11ConsensusProposal\x12A\n" +
	"\n" +
	"management\x18\x01 \x01(\v2\x1f.api.colonio.v1alpha.ManagementH\x00R\n" +
	"management\x12>\n" +
	"\toperation\x18\x02 \x01(\v2\x1e.api.colonio.v1alpha.OperationH\x00R\toperationB\t\n" +
	"\acontent\"\f\n" +
	"\n" +
	"Management\"\x80\x02\n" +
	"\tOperation\x12@\n" +
	"\acommand\x18\x01 \x01(\x0e2&.api.colonio.v1alpha.Operation.CommandR\acommand\x12!\n" +
	"\foperation_id\x18\x02 \x01(\rR\voperationId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"f\n" +
	"\aCommand\x12\x12\n" +
	"\x0eCOMMAND_IMPORT\x10\x00\x12\x0f\n" +
	"\vCOMMAND_GET\x10\x01\x12\x0f\n" +
	"\vCOMMAND_SET\x10\x02\x12\x11\n" +
	"\rCOMMAND_PATCH\x10\x03\x12\x12\n" +
	"\x0eCOMMAND_DELETE\x10\x04\"^\n" +
	"\x16ConsensusStateSnapshot\x12D\n" +
	"\arecords\x18\x01 \x01(\v2*.api.colonio.v1alpha.ConsensusStateRecordsR\arecords\"\xa6\x01\n" +
	"\x15ConsensusStateRecords\x12Q\n" +
	"\arecords\x18\x01 \x03(\v27.api.colonio.v1alpha.ConsensusStateRecords.RecordsEntryR\arecords\x1a:\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B5Z3github.com/llamerada-jp/colonio/api/colonio/v1alphab\x06proto3"

var (
	file_api_colonio_v1alpha_consensus_proto_rawDescOnce sync.Once
	file_api_colonio_v1alpha_consensus_proto_rawDescData []byte
)

func file_api_colonio_v1alpha_consensus_proto_rawDescGZIP() []byte {
	file_api_colonio_v1alpha_consensus_proto_rawDescOnce.Do(func() {
		file_api_colonio_v1alpha_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_colonio_v1alpha_consensus_proto_rawDesc), len(file_api_colonio_v1alpha_consensus_proto_rawDesc)))
	})
	return file_api_colonio_v1alpha_consensus_proto_rawDescData
}

var file_api_colonio_v1alpha_consensus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_colonio_v1alpha_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_colonio_v1alpha_consensus_proto_goTypes = []any{
	(Operation_Command)(0),         // 0: api.colonio.v1alpha.Operation.Command
	(*ConsensusProposal)(nil),      // 1: api.colonio.v1alpha.ConsensusProposal
	(*Management)(nil),             // 2: api.colonio.v1alpha.Management
	(*Operation)(nil),              // 3: api.colonio.v1alpha.Operation
	(*ConsensusStateSnapshot)(nil), // 4: api.colonio.v1alpha.ConsensusStateSnapshot
	(*ConsensusStateRecords)(nil),  // 5: api.colonio.v1alpha.ConsensusStateRecords
	nil,                            // 6: api.colonio.v1alpha.ConsensusStateRecords.RecordsEntry
}
var file_api_colonio_v1alpha_consensus_proto_depIdxs = []int32{
	2, // 0: api.colonio.v1alpha.ConsensusProposal.management:type_name -> api.colonio.v1alpha.Management
	3, // 1: api.colonio.v1alpha.ConsensusProposal.operation:type_name -> api.colonio.v1alpha.Operation
	0, // 2: api.colonio.v1alpha.Operation.command:type_name -> api.colonio.v1alpha.Operation.Command
	5, // 3: api.colonio.v1alpha.ConsensusStateSnapshot.records:type_name -> api.colonio.v1alpha.ConsensusStateRecords
	6, // 4: api.colonio.v1alpha.ConsensusStateRecords.records:type_name -> api.colonio.v1alpha.ConsensusStateRecords.RecordsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_colonio_v1alpha_consensus_proto_init() }
func file_api_colonio_v1alpha_consensus_proto_init() {
	if File_api_colonio_v1alpha_consensus_proto != nil {
		return
	}
	file_api_colonio_v1alpha_consensus_proto_msgTypes[0].OneofWrappers = []any{
		(*ConsensusProposal_Management)(nil),
		(*ConsensusProposal_Operation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_colonio_v1alpha_consensus_proto_rawDesc), len(file_api_colonio_v1alpha_consensus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_colonio_v1alpha_consensus_proto_goTypes,
		DependencyIndexes: file_api_colonio_v1alpha_consensus_proto_depIdxs,
		EnumInfos:         file_api_colonio_v1alpha_consensus_proto_enumTypes,
		MessageInfos:      file_api_colonio_v1alpha_consensus_proto_msgTypes,
	}.Build()
	File_api_colonio_v1alpha_consensus_proto = out.File
	file_api_colonio_v1alpha_consensus_proto_goTypes = nil
	file_api_colonio_v1alpha_consensus_proto_depIdxs = nil
}
