// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/node_accessor_protocol.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Carrier struct {
	Packet               []*Packet `protobuf:"bytes,1,rep,name=packet,proto3" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Carrier) Reset()         { *m = Carrier{} }
func (m *Carrier) String() string { return proto.CompactTextString(m) }
func (*Carrier) ProtoMessage()    {}
func (*Carrier) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{0}
}

func (m *Carrier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carrier.Unmarshal(m, b)
}
func (m *Carrier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carrier.Marshal(b, m, deterministic)
}
func (m *Carrier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carrier.Merge(m, src)
}
func (m *Carrier) XXX_Size() int {
	return xxx_messageInfo_Carrier.Size(m)
}
func (m *Carrier) XXX_DiscardUnknown() {
	xxx_messageInfo_Carrier.DiscardUnknown(m)
}

var xxx_messageInfo_Carrier proto.InternalMessageInfo

func (m *Carrier) GetPacket() []*Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

type Head struct {
	DstNid               *NodeID  `protobuf:"bytes,1,opt,name=dst_nid,json=dstNid,proto3" json:"dst_nid,omitempty"`
	SrcNid               *NodeID  `protobuf:"bytes,2,opt,name=src_nid,json=srcNid,proto3" json:"src_nid,omitempty"`
	HopCount             uint32   `protobuf:"varint,3,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	Mode                 uint32   `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Channel              uint32   `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	ModuleChannel        uint32   `protobuf:"varint,6,opt,name=module_channel,json=moduleChannel,proto3" json:"module_channel,omitempty"`
	CommandId            uint32   `protobuf:"varint,7,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{1}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetDstNid() *NodeID {
	if m != nil {
		return m.DstNid
	}
	return nil
}

func (m *Head) GetSrcNid() *NodeID {
	if m != nil {
		return m.SrcNid
	}
	return nil
}

func (m *Head) GetHopCount() uint32 {
	if m != nil {
		return m.HopCount
	}
	return 0
}

func (m *Head) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Head) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *Head) GetModuleChannel() uint32 {
	if m != nil {
		return m.ModuleChannel
	}
	return 0
}

func (m *Head) GetCommandId() uint32 {
	if m != nil {
		return m.CommandId
	}
	return 0
}

type Packet struct {
	// Enable head if index is 0.
	Head *Head `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// ID is common to sequence of packets.
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// index decreses by 1 in a sequance of packets.
	Index                uint32   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Content              []byte   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{2}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Packet) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Packet) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Packet) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ICE struct {
	LocalNid             *NodeID  `protobuf:"bytes,1,opt,name=local_nid,json=localNid,proto3" json:"local_nid,omitempty"`
	RemoteNid            *NodeID  `protobuf:"bytes,2,opt,name=remote_nid,json=remoteNid,proto3" json:"remote_nid,omitempty"`
	Ice                  string   `protobuf:"bytes,3,opt,name=ice,proto3" json:"ice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ICE) Reset()         { *m = ICE{} }
func (m *ICE) String() string { return proto.CompactTextString(m) }
func (*ICE) ProtoMessage()    {}
func (*ICE) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{3}
}

func (m *ICE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ICE.Unmarshal(m, b)
}
func (m *ICE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ICE.Marshal(b, m, deterministic)
}
func (m *ICE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICE.Merge(m, src)
}
func (m *ICE) XXX_Size() int {
	return xxx_messageInfo_ICE.Size(m)
}
func (m *ICE) XXX_DiscardUnknown() {
	xxx_messageInfo_ICE.DiscardUnknown(m)
}

var xxx_messageInfo_ICE proto.InternalMessageInfo

func (m *ICE) GetLocalNid() *NodeID {
	if m != nil {
		return m.LocalNid
	}
	return nil
}

func (m *ICE) GetRemoteNid() *NodeID {
	if m != nil {
		return m.RemoteNid
	}
	return nil
}

func (m *ICE) GetIce() string {
	if m != nil {
		return m.Ice
	}
	return ""
}

type Offer struct {
	PrimeNid             *NodeID  `protobuf:"bytes,1,opt,name=prime_nid,json=primeNid,proto3" json:"prime_nid,omitempty"`
	SecondNid            *NodeID  `protobuf:"bytes,2,opt,name=second_nid,json=secondNid,proto3" json:"second_nid,omitempty"`
	Sdp                  string   `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{4}
}

func (m *Offer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offer.Unmarshal(m, b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
}
func (m *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(m, src)
}
func (m *Offer) XXX_Size() int {
	return xxx_messageInfo_Offer.Size(m)
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetPrimeNid() *NodeID {
	if m != nil {
		return m.PrimeNid
	}
	return nil
}

func (m *Offer) GetSecondNid() *NodeID {
	if m != nil {
		return m.SecondNid
	}
	return nil
}

func (m *Offer) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

func (m *Offer) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type OfferSuccess struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	SecondNid            *NodeID  `protobuf:"bytes,2,opt,name=second_nid,json=secondNid,proto3" json:"second_nid,omitempty"`
	Sdp                  string   `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferSuccess) Reset()         { *m = OfferSuccess{} }
func (m *OfferSuccess) String() string { return proto.CompactTextString(m) }
func (*OfferSuccess) ProtoMessage()    {}
func (*OfferSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{5}
}

func (m *OfferSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferSuccess.Unmarshal(m, b)
}
func (m *OfferSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferSuccess.Marshal(b, m, deterministic)
}
func (m *OfferSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferSuccess.Merge(m, src)
}
func (m *OfferSuccess) XXX_Size() int {
	return xxx_messageInfo_OfferSuccess.Size(m)
}
func (m *OfferSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_OfferSuccess proto.InternalMessageInfo

func (m *OfferSuccess) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OfferSuccess) GetSecondNid() *NodeID {
	if m != nil {
		return m.SecondNid
	}
	return nil
}

func (m *OfferSuccess) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type OfferFailure struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	PrimeNid             *NodeID  `protobuf:"bytes,2,opt,name=prime_nid,json=primeNid,proto3" json:"prime_nid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferFailure) Reset()         { *m = OfferFailure{} }
func (m *OfferFailure) String() string { return proto.CompactTextString(m) }
func (*OfferFailure) ProtoMessage()    {}
func (*OfferFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6da5911fa8c514f, []int{6}
}

func (m *OfferFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferFailure.Unmarshal(m, b)
}
func (m *OfferFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferFailure.Marshal(b, m, deterministic)
}
func (m *OfferFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferFailure.Merge(m, src)
}
func (m *OfferFailure) XXX_Size() int {
	return xxx_messageInfo_OfferFailure.Size(m)
}
func (m *OfferFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferFailure.DiscardUnknown(m)
}

var xxx_messageInfo_OfferFailure proto.InternalMessageInfo

func (m *OfferFailure) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OfferFailure) GetPrimeNid() *NodeID {
	if m != nil {
		return m.PrimeNid
	}
	return nil
}

func init() {
	proto.RegisterType((*Carrier)(nil), "colonio.NodeAccessorProtocol.Carrier")
	proto.RegisterType((*Head)(nil), "colonio.NodeAccessorProtocol.Head")
	proto.RegisterType((*Packet)(nil), "colonio.NodeAccessorProtocol.Packet")
	proto.RegisterType((*ICE)(nil), "colonio.NodeAccessorProtocol.ICE")
	proto.RegisterType((*Offer)(nil), "colonio.NodeAccessorProtocol.Offer")
	proto.RegisterType((*OfferSuccess)(nil), "colonio.NodeAccessorProtocol.OfferSuccess")
	proto.RegisterType((*OfferFailure)(nil), "colonio.NodeAccessorProtocol.OfferFailure")
}

func init() { proto.RegisterFile("core/node_accessor_protocol.proto", fileDescriptor_d6da5911fa8c514f) }

var fileDescriptor_d6da5911fa8c514f = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4d, 0x8b, 0x13, 0x4d,
	0x10, 0xc7, 0x99, 0xbc, 0x4c, 0x36, 0xb5, 0x9b, 0x7d, 0x1e, 0x9a, 0x45, 0x06, 0x5f, 0x20, 0x0e,
	0x0a, 0xb9, 0x18, 0x71, 0x17, 0x3c, 0x79, 0xd1, 0xf8, 0x96, 0xcb, 0xba, 0x8c, 0x27, 0xbd, 0x0c,
	0x6d, 0x77, 0x2d, 0x69, 0x9c, 0xe9, 0x1a, 0xba, 0x3b, 0xa0, 0x27, 0xfd, 0x12, 0x7e, 0x54, 0xef,
	0xd2, 0x35, 0x9d, 0x05, 0x0f, 0x26, 0x1e, 0xbc, 0x0c, 0x55, 0x35, 0xbf, 0xae, 0xfa, 0xd7, 0xbf,
	0x69, 0xb8, 0xaf, 0xc8, 0xe1, 0x63, 0x4b, 0x1a, 0x6b, 0xa9, 0x14, 0x7a, 0x4f, 0xae, 0xee, 0x1c,
	0x05, 0x52, 0xd4, 0x2c, 0x39, 0x10, 0x77, 0x15, 0x35, 0x64, 0x0d, 0x2d, 0x2f, 0x49, 0xe3, 0xf3,
	0x04, 0x5d, 0x25, 0xe6, 0xf6, 0x7f, 0xdc, 0x20, 0x7e, 0x7a, 0xbc, 0x7c, 0x03, 0x93, 0x95, 0x74,
	0xce, 0xa0, 0x13, 0xcf, 0x20, 0xef, 0xa4, 0xfa, 0x8c, 0xa1, 0xc8, 0xe6, 0xc3, 0xc5, 0xf1, 0xf9,
	0x83, 0xe5, 0xbe, 0x56, 0xcb, 0x2b, 0x66, 0xab, 0x74, 0xa6, 0xfc, 0x99, 0xc1, 0xe8, 0x2d, 0x4a,
	0x2d, 0x1e, 0xc1, 0x44, 0xfb, 0x50, 0x5b, 0xa3, 0x8b, 0x6c, 0x9e, 0x2d, 0x8e, 0xcf, 0xcf, 0x6e,
	0xfa, 0xf0, 0xdc, 0xd8, 0x6c, 0xfd, 0xb2, 0xca, 0xb5, 0x0f, 0x97, 0x86, 0x71, 0xef, 0x14, 0xe3,
	0x83, 0x7d, 0xb8, 0x77, 0x2a, 0xe2, 0x77, 0x60, 0xba, 0xa1, 0xae, 0x56, 0xb4, 0xb5, 0xa1, 0x18,
	0xce, 0xb3, 0xc5, 0xac, 0x3a, 0xda, 0x50, 0xb7, 0x8a, 0xb9, 0x10, 0x30, 0x6a, 0x49, 0x63, 0x31,
	0xe2, 0x3a, 0xc7, 0xa2, 0x80, 0x89, 0xda, 0x48, 0x6b, 0xb1, 0x29, 0xc6, 0x5c, 0xde, 0xa5, 0xe2,
	0x21, 0x9c, 0xb6, 0xa4, 0xb7, 0x0d, 0xd6, 0x3b, 0x20, 0x67, 0x60, 0xd6, 0x57, 0x57, 0x09, 0xbb,
	0x07, 0xa0, 0xa8, 0x6d, 0xa5, 0xd5, 0xb5, 0xd1, 0xc5, 0x84, 0x91, 0x69, 0xaa, 0xac, 0x75, 0xf9,
	0x3d, 0x83, 0xbc, 0xb7, 0x42, 0x3c, 0x85, 0xd1, 0x06, 0xe5, 0x6e, 0xed, 0x72, 0xbf, 0x7d, 0xd1,
	0xab, 0x8a, 0x79, 0x71, 0x0a, 0x83, 0xb4, 0xfd, 0xac, 0x1a, 0x18, 0x2d, 0xce, 0x60, 0x6c, 0xac,
	0xc6, 0x2f, 0x69, 0xbf, 0x3e, 0xe1, 0x45, 0xc8, 0x06, 0xb4, 0x81, 0xf7, 0x3b, 0xa9, 0x76, 0x69,
	0xf9, 0x0d, 0x86, 0xeb, 0xd5, 0x2b, 0xf1, 0x04, 0xa6, 0x0d, 0x29, 0xd9, 0x1c, 0xb4, 0xfe, 0x88,
	0xb1, 0xe8, 0xe6, 0x05, 0x80, 0xc3, 0x96, 0x02, 0x1e, 0xf4, 0x7f, 0xda, 0x73, 0xf1, 0xd0, 0xff,
	0x30, 0x34, 0x0a, 0x59, 0xdc, 0xb4, 0x8a, 0x61, 0xf9, 0x23, 0x83, 0xf1, 0xbb, 0xeb, 0x6b, 0x74,
	0x51, 0x43, 0xe7, 0x4c, 0x8b, 0x87, 0x35, 0x30, 0x96, 0x34, 0x78, 0x54, 0x64, 0xf5, 0x61, 0x0d,
	0x3d, 0x97, 0x34, 0x78, 0xdd, 0xed, 0x34, 0x78, 0xdd, 0xc5, 0xbb, 0x0f, 0x5f, 0xbb, 0x9b, 0xbb,
	0x8f, 0x71, 0xd9, 0xc2, 0x09, 0xcb, 0x7a, 0xbf, 0x65, 0xf7, 0xc5, 0x2d, 0xc8, 0x7d, 0x90, 0x61,
	0xeb, 0x59, 0xda, 0xac, 0x4a, 0xd9, 0x3f, 0x92, 0x50, 0x7e, 0x48, 0xe3, 0x5e, 0x4b, 0xd3, 0x6c,
	0x1d, 0xfe, 0x71, 0xdc, 0x6f, 0x26, 0x0d, 0xfe, 0xc6, 0xa4, 0x17, 0xf9, 0xc7, 0x51, 0xfc, 0xf1,
	0x29, 0xe7, 0x57, 0x7b, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x8b, 0x2a, 0xd9, 0x09, 0x04,
	0x00, 0x00,
}
