name: test
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  build-native:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: make setup build

  build-docker:
    name: build with docker
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: docker build .