name: CI
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  native:
    name: test on ${{ matrix.os }} amd64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Cache setup files
      uses: actions/cache@v2
      with:
        path: ci_cache
        key: ${{ runner.os }}-${{ hashFiles('Makefile') }}
    - shell: bash
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        ./ci.sh
  # qemu:
  #   name: test on ubuntu-20.04 arm64
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: uraimo/run-on-arch-action@v2.0.5
  #     name: run test
  #     id: cmd
  #     with:
  #       arch: aarch64
  #       distro: ubuntu20.04
  #       githubToken: ${{ github.token }}
  #       env: |
  #         DEBIAN_FRONTEND: noninteractive
  #       install: |
  #         apt-get update -q -y
  #         apt-get install -q -y cmake curl docker.io golang-1.14 make sudo systemctl unzip
  #         systemctl enable --now docker
  #       run: |
  #         ./ci.sh
