name: Main
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - run: make setup build
